      - api_url: "https://api.telegram.org"
        chat_id: 
        bot_token: 
        send_resolved: true
        parse_mode: "HTML"

  - name: "telegram-alert"
    telegram_configs:
      - api_url: "https://api.telegram.org"
        chat_id: 
        bot_token: 
        send_resolved: true
        parse_mode: "HTML"

  # WEBHOOK RECEIVER (BẠN TỰ CÓ API)
  - name: "webhook"
    webhook_configs:
      - url: "http://api.my-alert.com/alert/7204342151"
        send_resolved: true

# INHIBIT RULES (GIỮ NGUYÊN)
inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname"]

  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["zone"]

  - source_match:
      severity: "critical"
    target_match:
      severity: "error"
    equal: ["zone"]
