---
- name: Cập nhật cache của hệ thống (apt update)
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Cài đặt các gói phần mềm nền tảng
  apt:
    name:
      - ntp
      - rsyslog
      - logrotate
      - curl
      - unzip
    state: present

- name: Đảm bảo múi giờ hệ thống là Asia/Ho_Chi_Minh
  timezone:
    name: Asia/Ho_Chi_Minh

- name: Khởi động và kích hoạt dịch vụ NTP (Đồng bộ giờ)
  systemctl:
    name: ntp
    state: started
    enabled: yes
