









---
- name: Setup Monitoring Agents
  hosts: all
  become: yes
  vars_files:
    - secrets.yml  # Gọi file bí mật ở đây
  
  tasks:
    - name: Cai dat Node Exporter
      apt:
        name: prometheus-node-exporter
        state: present

    - name: Day script all-in-one len may con
      copy:
        src: ./script/all-in-one.sh
        dest: /usr/local/bin/all-in-one.sh
        mode: '0755'

    - name: Thong bao qua Telegram bot
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: "🚀 Ansible đã cấu hình xong Node Exporter trên {{ inventory_hostname }}"
